In [ ]:
import pandas as pd
df = pd.read_excel('Dataset.xlsx')
df.head()

  Location  IMIPENEM  CEFTAZIDIME  GENTAMICIN  AUGMENTIN  CIPROFLOXACIN
0    IFE-T        25           20          20         15             28
1    IFE-T        25           25          20         20             30
2    IFE-T        30           10          20         20             25
3    IFE-T        25           20          20         25             28
4    IFE-T        25            7          20         20             22

In [2]:
df.info

<bound method DataFrame.info of     Location  IMIPENEM  CEFTAZIDIME  GENTAMICIN  AUGMENTIN  CIPROFLOXACIN
0      IFE-T        25           20          20         15             28
1      IFE-T        25           25          20         20             30
2      IFE-T        30           10          20         20             25
3      IFE-T        25           20          20         25             28
4      IFE-T        25            7          20         20             22
..       ...       ...          ...         ...        ...            ...
269    EDE-S        33            0           0         12             25
270    EDE-S        30            0          20         12             23
271    EDE-S        23           30          20         12             35
272    EDE-S        21            0          18         12             20
273    EDE-S        24            0          22         11             23

[274 rows x 6 columns]>

In [3]:
df.describe()

         IMIPENEM  CEFTAZIDIME  GENTAMICIN   AUGMENTIN  CIPROFLOXACIN
count  274.000000   274.000000  274.000000  274.000000     274.000000
mean    24.430657     8.605839   16.806569   11.237226      19.138686
std      5.788451     8.996017    5.553848    8.141060       7.936269
min      0.000000     0.000000    0.000000    0.000000       0.000000
25%     20.000000     0.000000   15.000000    1.000000      17.000000
50%     24.000000     8.500000   18.000000   12.000000      21.000000
75%     28.000000    15.000000   20.000000   17.000000      25.000000
max     40.000000    32.000000   30.000000   35.000000      35.000000